"""Alliances

Revision ID: c63d4a434956
Revises: db168dafe179
Create Date: 2021-09-23 21:53:28.085150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.sql import expression

revision = "c63d4a434956"
down_revision = "db168dafe179"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("groups_world")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_accounts_guid"), ["guid"])
        batch_op.create_unique_constraint(batch_op.f("uq_accounts_name"), ["name"])

    with op.batch_alter_table("guilds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_part_of_alliance",
                sa.Boolean(),
                server_default=expression.false(),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guilds", schema=None) as batch_op:
        batch_op.drop_column("is_part_of_alliance")

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_accounts_name"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_accounts_guid"), type_="unique")

    op.create_table(
        "groups_world",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("group_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "world",
            sa.Enum(
                "ANVIL_ROCK",
                "BORLIS_PASS",
                "YAKS_BEND",
                "HENGE_OF_DENRAVI",
                "MAGUUMA",
                "SORROWS_FURNACE",
                "GATE_OF_MADNESS",
                "JADE_QUARRY",
                "FORT_ASPENWOOD",
                "EHMRY_BAY",
                "STORMBLUFF_ISLE",
                "DARKHAVEN",
                "SANCTUM_OF_RALL",
                "CRYSTAL_DESERT",
                "ISLE_OF_JANTHIR",
                "SEA_OF_SORROWS",
                "TARNISHED_COAST",
                "NORTHERN_SHIVERPEAKS",
                "BLACKGATE",
                "FERGUSONS_CROSSING",
                "DRAGONBRAND",
                "KAINENG",
                "DEVONAS_REST",
                "EREDON_TERRACE",
                "FISSURE_OF_WOE",
                "DESOLATION",
                "GANDARA",
                "BLACKTIDE",
                "RING_OF_FIRE",
                "UNDERWORLD",
                "FAR_SHIVERPEAKS",
                "WHITESIDE_RIDGE",
                "RUINS_OF_SURMIA",
                "SEAFARERS_REST",
                "VABBI",
                "PIKEN_SQUARE",
                "AURORA_GLADE",
                "GUNNARS_HOLD",
                "JADE_SEA",
                "FORT_RANIK",
                "AUGURY_ROCK",
                "VIZUNAH_SQUARE",
                "ARBORSTONE",
                "KODASH",
                "RIVERSIDE",
                "ELONA_REACH",
                "ABADDONS_MOUTH",
                "DRAKKAR_LAKE",
                "MILLERS_SOUND",
                "DZAGONUR",
                "BARUCH_BAY",
                name="world",
            ),
            nullable=False,
        ),
        sa.Column("is_linked", sa.BOOLEAN(), nullable=False),
        sa.CheckConstraint("is_linked IN (0, 1)", name="ck_groups_world_is_linked"),
        sa.PrimaryKeyConstraint("id", name="pk_groups_world"),
        sa.UniqueConstraint("group_id", name="uq_groups_world_group_id"),
        sa.UniqueConstraint("world", name="uq_groups_world_world"),
    )

    # ### end Alembic commands ###
