"""Add retry count to account table

Revision ID: db168dafe179
Revises: 2b6daf0b7566
Create Date: 2020-10-16 18:31:25.047238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db168dafe179'
down_revision = '2b6daf0b7566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('retries', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'retries')
    # ### end Alembic commands ###
